/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package solutions.sulfura.gend;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

}
