repositories {
    mavenCentral()
}

dependencies {
    project(":hyperkit-dto-generator-core")
}

// To avoid manual errors when changing the project version, the pom.xml is autogenerated from a template.
// It is done with a template instead of using a variable in the pom.xml file because deploying the plugin requires the version to not be derived from a variable
val generatePomFromTemplate by tasks.registering() {
    group = "build"
    description =
        "Uses pom.xml.templ as a template to create the pom.xml file that will be used to run the plugin building tasks"

    val templateFile = layout.projectDirectory.file("pom.xml.templ")
    val outputFile = layout.projectDirectory.file("pom.xml")

    // Declare inputs/outputs for Gradle up-to-date checks
    inputs.file(templateFile)
    outputs.file(outputFile)

    // Template variables
    val propsProvider = providers.provider {
        mapOf(
            "hyperkit.version" to project.version.toString()
        )
    }

    val props = propsProvider.get()
    inputs.properties(props)

    doLast {

        val template = templateFile.asFile.readText(Charsets.UTF_8)

        val rendered = props.entries.fold(template) { acc, (k, v) ->
            acc.replace("{{$k}}", v)
        }

        val out = outputFile.asFile
        out.parentFile.mkdirs()
        out.writeText(rendered, Charsets.UTF_8)

    }
}

val clean by tasks.registering(MavenExec::class) {
    group = "build"
    workingDir = project.projectDir
    mavenGoal = "clean"
    args("-Dhyperkit.version=$version")
}

val compile by tasks.registering(MavenExec::class) {
    group = "build"
    workingDir = project.projectDir
    mavenGoal = "compile"
    args("-Dhyperkit.version=$version")
    dependsOn(generatePomFromTemplate)
    dependsOn(":hyperkit-dto-generator-core:publishMavenPublicationToMavenLocal")
}

val test by tasks.registering(MavenExec::class) {
    group = "build"
    workingDir = project.projectDir
    mavenGoal = "test"
    args("-Dhyperkit.version=$version")
    dependsOn(generatePomFromTemplate)
}

val install by tasks.registering(MavenExec::class) {
    group = "publishing"
    workingDir = project.projectDir
    mavenGoal = "install"
    args("-Dhyperkit.version=$version")
    dependsOn(generatePomFromTemplate)
}

val deploy by tasks.registering(MavenExec::class) {
    group = "publishing"
    workingDir = project.projectDir
    mavenGoal = "deploy"
    args("-Dhyperkit.version=$version")
    dependsOn(generatePomFromTemplate)
    args = mutableListOf("-s", "settings.xml")
}