-- liquibase formatted sql

-- changeset hyperkit-example:1
CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL
);

CREATE TABLE app_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content CLOB,
    author_id BIGINT NOT NULL,
    CONSTRAINT fk_post_author FOREIGN KEY (author_id) REFERENCES app_users(id)
);

-- rollback drop table posts;
-- rollback drop table users;