package solutions.sulfura.hyperkit.test.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Column;
import jakarta.persistence.Id;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import java.util.Objects;

/**
 * Entity class for the CATEGORY table.
 * Generated by HyperKit Entity Generator.
 */
@Entity
@Table(name = "CATEGORY", schema = "PUBLIC")
public class Category {

    // <fields>
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID", nullable = false)
    private Long id;
    @Column(name = "NAME", nullable = false)
    private String name;
    @Column(name = "DESCRIPTION")
    private String description;

    // </fields>

    public Category() {
    }

    // <getters-setters>
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    // </getters-setters>

    public static Builder builder() {
        return new Builder();
    }

    // <builder>
    public static class Builder {

        private Category instance = new Category();

        public Category build() {
            return instance;
        }

        public Builder id(Long id) {
            instance.id = id;
            return this;
        }

        public Builder name(String name) {
            instance.name = name;
            return this;
        }

        public Builder description(String description) {
            instance.description = description;
            return this;
        }

    }

    // </builder>

}