package solutions.sulfura.hyperkit.test.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Column;
import jakarta.persistence.Id;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.JoinColumn;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Objects;

/**
 * Entity class for the ORDERS table.
 * Generated by HyperKit Entity Generator.
 */
@Entity
@Table(name = "ORDERS", schema = "PUBLIC")
public class Orders {

    // <fields>
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID", nullable = false)
    private Long id;
    @Column(name = "USER_ID", nullable = false)
    private Long userId;
    @Column(name = "ORDER_DATE", nullable = false)
    private LocalDateTime orderDate;
    @Column(name = "STATUS", nullable = false)
    private String status;
    @Column(name = "TOTAL_AMOUNT", nullable = false)
    private BigDecimal totalAmount;
    @ManyToOne
    @JoinColumn(name = "USER_ID")
    private AppUser appUser;

    // </fields>

    public Orders() {
    }

    // <getters-setters>
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public LocalDateTime getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(LocalDateTime orderDate) {
        this.orderDate = orderDate;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    public AppUser getAppUser() {
        return appUser;
    }

    public void setAppUser(AppUser appUser) {
        this.appUser = appUser;
    }

    // </getters-setters>

    public static Builder builder() {
        return new Builder();
    }

    // <builder>
    public static class Builder {

        private Orders instance = new Orders();

        public Orders build() {
            return instance;
        }

        public Builder id(Long id) {
            instance.id = id;
            return this;
        }

        public Builder userId(Long userId) {
            instance.userId = userId;
            return this;
        }

        public Builder orderDate(LocalDateTime orderDate) {
            instance.orderDate = orderDate;
            return this;
        }

        public Builder status(String status) {
            instance.status = status;
            return this;
        }

        public Builder totalAmount(BigDecimal totalAmount) {
            instance.totalAmount = totalAmount;
            return this;
        }

        public Builder appUser(AppUser appUser) {
            instance.userPreferences = appUser;
            return this;
        }

    }

    // </builder>

}