package solutions.sulfura.hyperkit.test.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Column;
import jakarta.persistence.Id;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.JoinColumn;
import java.math.BigDecimal;
import java.util.Objects;

/**
 * Entity class for the ORDER_ITEM table.
 * Generated by HyperKit Entity Generator.
 */
@Entity
@Table(name = "ORDER_ITEM", schema = "PUBLIC")
public class OrderItem {

    // <fields>
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID", nullable = false)
    private Long id;
    @Column(name = "ORDER_ID", nullable = false)
    private Long orderId;
    @Column(name = "PRODUCT_ID", nullable = false)
    private Long productId;
    @Column(name = "QUANTITY", nullable = false)
    private Integer quantity;
    @Column(name = "PRICE", nullable = false)
    private BigDecimal price;
    @ManyToOne
    @JoinColumn(name = "ORDER_ID")
    private Orders orders;
    @ManyToOne
    @JoinColumn(name = "PRODUCT_ID")
    private Product product;

    // </fields>

    public OrderItem() {
    }

    // <getters-setters>
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getOrderId() {
        return orderId;
    }

    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public Orders getOrders() {
        return orders;
    }

    public void setOrders(Orders orders) {
        this.orders = orders;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    // </getters-setters>

    public static Builder builder() {
        return new Builder();
    }

    // <builder>
    public static class Builder {

        private OrderItem instance = new OrderItem();

        public OrderItem build() {
            return instance;
        }

        public Builder id(Long id) {
            instance.id = id;
            return this;
        }

        public Builder orderId(Long orderId) {
            instance.orderId = orderId;
            return this;
        }

        public Builder productId(Long productId) {
            instance.productId = productId;
            return this;
        }

        public Builder quantity(Integer quantity) {
            instance.quantity = quantity;
            return this;
        }

        public Builder price(BigDecimal price) {
            instance.price = price;
            return this;
        }

        public Builder orders(Orders orders) {
            instance.userPreferences = orders;
            return this;
        }

        public Builder product(Product product) {
            instance.userPreferences = product;
            return this;
        }

    }

    // </builder>

}