package solutions.sulfura.hyperkit.test.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Column;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.JoinColumn;
import java.util.Objects;

/**
 * Entity class for the PRODUCT__CATEGORY table.
 * Generated by HyperKit Entity Generator.
 */
@Entity
@Table(name = "PRODUCT__CATEGORY", schema = "PUBLIC")
public class ProductCategory {

    // <fields>
    @Id
    @Column(name = "PRODUCT__CATEGORY_ID", nullable = false)
    private Long productCategoryId;
    @Column(name = "PRODUCT_ID", nullable = false)
    private Long productId;
    @Column(name = "CATEGORY_ID", nullable = false)
    private Long categoryId;
    @ManyToOne
    @JoinColumn(name = "CATEGORY_ID")
    private Category category;
    @ManyToOne
    @JoinColumn(name = "PRODUCT_ID")
    private Product product;

    // </fields>

    public ProductCategory() {
    }

    // <getters-setters>
    public Long getProductCategoryId() {
        return productCategoryId;
    }

    public void setProductCategoryId(Long productCategoryId) {
        this.productCategoryId = productCategoryId;
    }

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public Long getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    // </getters-setters>

    public static Builder builder() {
        return new Builder();
    }

    // <builder>
    public static class Builder {

        private ProductCategory instance = new ProductCategory();

        public ProductCategory build() {
            return instance;
        }

        public Builder productCategoryId(Long productCategoryId) {
            instance.productCategoryId = productCategoryId;
            return this;
        }

        public Builder productId(Long productId) {
            instance.productId = productId;
            return this;
        }

        public Builder categoryId(Long categoryId) {
            instance.categoryId = categoryId;
            return this;
        }

        public Builder category(Category category) {
            instance.category = category;
            return this;
        }

        public Builder product(Product product) {
            instance.product = product;
            return this;
        }

    }

    // </builder>

}